---
- name: Create admin user
  user:
    name: '{{ ansible_user }}'
    comment: 'admin user'
    shell: /bin/bash

- name: Add administrator authorized key
  authorized_key:
    user: '{{ ansible_user }}'
    key: "{{ lookup('file', admin_public_ssh_key | default('~/.ssh/id_rsa.pub')) }}"
    exclusive: yes

- name: Allow sudo for administrator
  copy:
    content: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    dest: '/etc/sudoers.d/{{ ansible_user }}'
    mode: '0600'