- name: Disable port 22 and enable custom ssh port on ssh config
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regex: '^Port 22'
    line: 'Port {{ ssh_port }}'
    state: present
    create: true
  tags:
    - ssh

- name: Disable root login over SSH
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  when: disable_root|default(true)|bool == true
  tags:
    - ssh

- name: Disable password login
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  tags:
    - ssh

- name: Enable public key authentication
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present
  tags:
    - ssh

- name: Allow ansible_user user only
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ ansible_user }}'
    state: present
  tags:
    - ssh

- name: Restart SSH
  service:
    name: ssh
    state: restarted
  changed_when: false
  tags:
    - ssh